/* 
 * Horizon Server API
 *
 * Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = VMware.Horizon.RESTAPI.Client.SwaggerDateConverter;

namespace VMware.Horizon.RESTAPI.Model
{
    /// <summary>
    /// Update specification for the instant clone domain account.
    /// </summary>
    [DataContract]
    public partial class InstantCloneDomainAccountUpdateSpec :  IEquatable<InstantCloneDomainAccountUpdateSpec>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstantCloneDomainAccountUpdateSpec" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InstantCloneDomainAccountUpdateSpec() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InstantCloneDomainAccountUpdateSpec" /> class.
        /// </summary>
        /// <param name="password">Password of the account. (required).</param>
        public InstantCloneDomainAccountUpdateSpec(List<string> password = default(List<string>))
        {
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new InvalidDataException("password is a required property for InstantCloneDomainAccountUpdateSpec and cannot be null");
            }
            else
            {
                this.Password = password;
            }
        }
        
        /// <summary>
        /// Password of the account.
        /// </summary>
        /// <value>Password of the account.</value>
        [DataMember(Name="password", EmitDefaultValue=false)]
        public List<string> Password { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InstantCloneDomainAccountUpdateSpec {\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InstantCloneDomainAccountUpdateSpec);
        }

        /// <summary>
        /// Returns true if InstantCloneDomainAccountUpdateSpec instances are equal
        /// </summary>
        /// <param name="input">Instance of InstantCloneDomainAccountUpdateSpec to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InstantCloneDomainAccountUpdateSpec input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Password == input.Password ||
                    this.Password != null &&
                    this.Password.SequenceEqual(input.Password)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Password != null)
                    hashCode = hashCode * 59 + this.Password.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
