/* 
 * Horizon Server API
 *
 * Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = VMware.Horizon.RESTAPI.Client.SwaggerDateConverter;

namespace VMware.Horizon.RESTAPI.Model
{
    /// <summary>
    /// PodEndPointDataV2
    /// </summary>
    [DataContract]
    public partial class PodEndPointDataV2 :  IEquatable<PodEndPointDataV2>, IValidatableObject
    {
        /// <summary>
        /// Status of the pod endpoint. * ONLINE: Pod endpoint is online and functional. * UNCHECKED: Pod endpoint was offline and it just came back online but the system has not verified that it is functional. * OFFLINE: Pod endpoint is offline or unreachable.
        /// </summary>
        /// <value>Status of the pod endpoint. * ONLINE: Pod endpoint is online and functional. * UNCHECKED: Pod endpoint was offline and it just came back online but the system has not verified that it is functional. * OFFLINE: Pod endpoint is offline or unreachable.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum ONLINE for value: ONLINE
            /// </summary>
            [EnumMember(Value = "ONLINE")]
            ONLINE = 1,
            
            /// <summary>
            /// Enum UNCHECKED for value: UNCHECKED
            /// </summary>
            [EnumMember(Value = "UNCHECKED")]
            UNCHECKED = 2,
            
            /// <summary>
            /// Enum OFFLINE for value: OFFLINE
            /// </summary>
            [EnumMember(Value = "OFFLINE")]
            OFFLINE = 3
        }

        /// <summary>
        /// Status of the pod endpoint. * ONLINE: Pod endpoint is online and functional. * UNCHECKED: Pod endpoint was offline and it just came back online but the system has not verified that it is functional. * OFFLINE: Pod endpoint is offline or unreachable.
        /// </summary>
        /// <value>Status of the pod endpoint. * ONLINE: Pod endpoint is online and functional. * UNCHECKED: Pod endpoint was offline and it just came back online but the system has not verified that it is functional. * OFFLINE: Pod endpoint is offline or unreachable.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PodEndPointDataV2" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PodEndPointDataV2() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PodEndPointDataV2" /> class.
        /// </summary>
        /// <param name="enabled">Indicates whether an endpoint is enabled. A disabled endpoint will be excluded from participating inter-pod communication. (required).</param>
        /// <param name="id">Unique ID for a pod endpoint. (required).</param>
        /// <param name="lastUpdatedTimestamp">The timestamp in milliseconds when the last update was obtained. Measured as epoch time..</param>
        /// <param name="name">Name for the pod endpoint. (required).</param>
        /// <param name="roundtripTime">Round trip time (in milliseconds) for ping request between the local pod endpoint and the remote pod..</param>
        /// <param name="status">Status of the pod endpoint. * ONLINE: Pod endpoint is online and functional. * UNCHECKED: Pod endpoint was offline and it just came back online but the system has not verified that it is functional. * OFFLINE: Pod endpoint is offline or unreachable. (required).</param>
        /// <param name="url">The URL for the pod endpoint. This address and special port will be used for inter-pod communication. (required).</param>
        public PodEndPointDataV2(bool? enabled = default(bool?), string id = default(string), long? lastUpdatedTimestamp = default(long?), string name = default(string), long? roundtripTime = default(long?), StatusEnum status = default(StatusEnum), string url = default(string))
        {
            // to ensure "enabled" is required (not null)
            if (enabled == null)
            {
                throw new InvalidDataException("enabled is a required property for PodEndPointDataV2 and cannot be null");
            }
            else
            {
                this.Enabled = enabled;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for PodEndPointDataV2 and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for PodEndPointDataV2 and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for PodEndPointDataV2 and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new InvalidDataException("url is a required property for PodEndPointDataV2 and cannot be null");
            }
            else
            {
                this.Url = url;
            }
            this.LastUpdatedTimestamp = lastUpdatedTimestamp;
            this.RoundtripTime = roundtripTime;
        }
        
        /// <summary>
        /// Indicates whether an endpoint is enabled. A disabled endpoint will be excluded from participating inter-pod communication.
        /// </summary>
        /// <value>Indicates whether an endpoint is enabled. A disabled endpoint will be excluded from participating inter-pod communication.</value>
        [DataMember(Name="enabled", EmitDefaultValue=false)]
        public bool? Enabled { get; set; }

        /// <summary>
        /// Unique ID for a pod endpoint.
        /// </summary>
        /// <value>Unique ID for a pod endpoint.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The timestamp in milliseconds when the last update was obtained. Measured as epoch time.
        /// </summary>
        /// <value>The timestamp in milliseconds when the last update was obtained. Measured as epoch time.</value>
        [DataMember(Name="last_updated_timestamp", EmitDefaultValue=false)]
        public long? LastUpdatedTimestamp { get; set; }

        /// <summary>
        /// Name for the pod endpoint.
        /// </summary>
        /// <value>Name for the pod endpoint.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Round trip time (in milliseconds) for ping request between the local pod endpoint and the remote pod.
        /// </summary>
        /// <value>Round trip time (in milliseconds) for ping request between the local pod endpoint and the remote pod.</value>
        [DataMember(Name="roundtrip_time", EmitDefaultValue=false)]
        public long? RoundtripTime { get; set; }


        /// <summary>
        /// The URL for the pod endpoint. This address and special port will be used for inter-pod communication.
        /// </summary>
        /// <value>The URL for the pod endpoint. This address and special port will be used for inter-pod communication.</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PodEndPointDataV2 {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LastUpdatedTimestamp: ").Append(LastUpdatedTimestamp).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RoundtripTime: ").Append(RoundtripTime).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PodEndPointDataV2);
        }

        /// <summary>
        /// Returns true if PodEndPointDataV2 instances are equal
        /// </summary>
        /// <param name="input">Instance of PodEndPointDataV2 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PodEndPointDataV2 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Enabled == input.Enabled ||
                    (this.Enabled != null &&
                    this.Enabled.Equals(input.Enabled))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.LastUpdatedTimestamp == input.LastUpdatedTimestamp ||
                    (this.LastUpdatedTimestamp != null &&
                    this.LastUpdatedTimestamp.Equals(input.LastUpdatedTimestamp))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.RoundtripTime == input.RoundtripTime ||
                    (this.RoundtripTime != null &&
                    this.RoundtripTime.Equals(input.RoundtripTime))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Enabled != null)
                    hashCode = hashCode * 59 + this.Enabled.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.LastUpdatedTimestamp != null)
                    hashCode = hashCode * 59 + this.LastUpdatedTimestamp.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.RoundtripTime != null)
                    hashCode = hashCode * 59 + this.RoundtripTime.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
