/* 
 * Horizon Server API
 *
 * Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = VMware.Horizon.RESTAPI.Client.SwaggerDateConverter;

namespace VMware.Horizon.RESTAPI.Model
{
    /// <summary>
    /// Client data associated with the session.
    /// </summary>
    [DataContract]
    public partial class ClientData :  IEquatable<ClientData>
    {
        /// <summary>
        /// Client type for the session.  This property need not be set. * WINDOWS: Client type is Windows client. * MAC: Client type is Mac client. * HTMLACCESS: Client type is Web client. * LINUX: Client type is Linux client. * IOS: Client type is iOS client. * ANDROID: Client type is Android client. * OTHER: Client type is other.
        /// </summary>
        /// <value>Client type for the session.  This property need not be set. * WINDOWS: Client type is Windows client. * MAC: Client type is Mac client. * HTMLACCESS: Client type is Web client. * LINUX: Client type is Linux client. * IOS: Client type is iOS client. * ANDROID: Client type is Android client. * OTHER: Client type is other.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum WINDOWS for value: WINDOWS
            /// </summary>
            [EnumMember(Value = "WINDOWS")]
            WINDOWS = 1,
            
            /// <summary>
            /// Enum MAC for value: MAC
            /// </summary>
            [EnumMember(Value = "MAC")]
            MAC = 2,
            
            /// <summary>
            /// Enum HTMLACCESS for value: HTMLACCESS
            /// </summary>
            [EnumMember(Value = "HTMLACCESS")]
            HTMLACCESS = 3,
            
            /// <summary>
            /// Enum LINUX for value: LINUX
            /// </summary>
            [EnumMember(Value = "LINUX")]
            LINUX = 4,
            
            /// <summary>
            /// Enum IOS for value: IOS
            /// </summary>
            [EnumMember(Value = "IOS")]
            IOS = 5,
            
            /// <summary>
            /// Enum ANDROID for value: ANDROID
            /// </summary>
            [EnumMember(Value = "ANDROID")]
            ANDROID = 6,
            
            /// <summary>
            /// Enum OTHER for value: OTHER
            /// </summary>
            [EnumMember(Value = "OTHER")]
            OTHER = 7
        }

        /// <summary>
        /// Client type for the session.  This property need not be set. * WINDOWS: Client type is Windows client. * MAC: Client type is Mac client. * HTMLACCESS: Client type is Web client. * LINUX: Client type is Linux client. * IOS: Client type is iOS client. * ANDROID: Client type is Android client. * OTHER: Client type is other.
        /// </summary>
        /// <value>Client type for the session.  This property need not be set. * WINDOWS: Client type is Windows client. * MAC: Client type is Mac client. * HTMLACCESS: Client type is Web client. * LINUX: Client type is Linux client. * IOS: Client type is iOS client. * ANDROID: Client type is Android client. * OTHER: Client type is other.</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClientData" /> class.
        /// </summary>
        /// <param name="address">IP address of the client machine for the session.  This property need not be set..</param>
        /// <param name="locationId">Client location for the session.  This property need not be set..</param>
        /// <param name="name">Client machine hostname for the session.  This property need not be set..</param>
        /// <param name="type">Client type for the session.  This property need not be set. * WINDOWS: Client type is Windows client. * MAC: Client type is Mac client. * HTMLACCESS: Client type is Web client. * LINUX: Client type is Linux client. * IOS: Client type is iOS client. * ANDROID: Client type is Android client. * OTHER: Client type is other..</param>
        /// <param name="version">Client version for the session.  This property need not be set..</param>
        public ClientData(string address = default(string), string locationId = default(string), string name = default(string), TypeEnum? type = default(TypeEnum?), string version = default(string))
        {
            this.Address = address;
            this.LocationId = locationId;
            this.Name = name;
            this.Type = type;
            this.Version = version;
        }
        
        /// <summary>
        /// IP address of the client machine for the session.  This property need not be set.
        /// </summary>
        /// <value>IP address of the client machine for the session.  This property need not be set.</value>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public string Address { get; set; }

        /// <summary>
        /// Client location for the session.  This property need not be set.
        /// </summary>
        /// <value>Client location for the session.  This property need not be set.</value>
        [DataMember(Name="location_id", EmitDefaultValue=false)]
        public string LocationId { get; set; }

        /// <summary>
        /// Client machine hostname for the session.  This property need not be set.
        /// </summary>
        /// <value>Client machine hostname for the session.  This property need not be set.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }


        /// <summary>
        /// Client version for the session.  This property need not be set.
        /// </summary>
        /// <value>Client version for the session.  This property need not be set.</value>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string Version { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClientData {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  LocationId: ").Append(LocationId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ClientData);
        }

        /// <summary>
        /// Returns true if ClientData instances are equal
        /// </summary>
        /// <param name="input">Instance of ClientData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClientData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.LocationId == input.LocationId ||
                    (this.LocationId != null &&
                    this.LocationId.Equals(input.LocationId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Version == input.Version ||
                    (this.Version != null &&
                    this.Version.Equals(input.Version))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.LocationId != null)
                    hashCode = hashCode * 59 + this.LocationId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Version != null)
                    hashCode = hashCode * 59 + this.Version.GetHashCode();
                return hashCode;
            }
        }
    }

}
